// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gemnvaszgqsyzbgitrve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlbW52YXN6Z3FzeXpiZ2l0cnZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTA5NDYsImV4cCI6MjA2NTY4Njk0Nn0._G7DuPcm8rG6GOEK-4w6jtakqH40s4qSwZQ0vjDs9L0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);